name: Deploy Create React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: mysql://kuzovok11_ermdev:Vanya825!@quabeejecubo.beget.app:3306/kuzovok11_ermdev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build the project
        run: npm run build

      - name: Archive build artifacts
        run: |
          mkdir -p artifacts
          cp -r .next artifacts/next
          cp -r prisma artifacts/prisma 
          cp -r public artifacts/public 
          cp -r package-lock.json artifacts/package-lock.json 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

      - name: Restore .next folder in artifacts
        run: |
          cp -r artifacts/next artifacts/.next
          rm -rf artifacts/next

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H kuzovok11.beget.tech >> ~/.ssh/known_hosts

      - name: Copy files to server via SSH
        run: |
          sshpass -p "dsfb332#2" rsync -avz ./artifacts/ kuzovok11@kuzovok11.beget.tech:/home/k/kuzovok11/erm.kuzovok11.ru/website

      - name: Touch restart file
        run: |
          sshpass -p "dsfb332#2" ssh -o StrictHostKeyChecking=no \
              kuzovok11@kuzovok11.beget.tech \
              "touch /home/k/kuzovok11/erm.kuzovok11.ru/website/tmp/restart.txt"

      - name: Clean up after deployment
        run: echo "Deployment completed successfully!"